using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Cidonix.UniBridge.MCP.Editor.Helpers;
using Cidonix.UniBridge.MCP.Editor.Tools;
using UnityEditor;
using UnityEditor.AssetImporters;
using UnityEngine;
using UnityEngine.UIElements;

namespace Cidonix.UniBridge.UIToolkitRegression
{
    public static class Regression
    {
        const string Uxml="<ui:UXML xmlns:ui=\"UnityEngine.UIElements\"><ui:VisualElement name=\"root\"><ui:Label name=\"title\" text=\"Вітаю &amp; hello\" /></ui:VisualElement></ui:UXML>";
        const string Uss=".root { width: 120px; color: rgb(12, 32, 48); --caption: \"a;b:c{}/*literal*/\"; }";
        const string BindingUxml="<ui:UXML xmlns:ui=\"UnityEngine.UIElements\"><ui:Label text=\"example\"><Bindings><ui:DataBinding property=\"text\" data-source-path=\"PlayerName\" /></Bindings></ui:Label></ui:UXML>";
        static readonly List<object> Cases=new();
        static string FixtureRoot="",Filter="";
        static int Sequence;
        static int Main(string[] args)
        {
            var report=Path.GetFullPath(args[0]);Filter=args.Length>2?args[2]:"";
            FixtureRoot=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"UniBridgeRegression","UIToolkit_"+Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(FixtureRoot);
            File.WriteAllText(Path.Combine(FixtureRoot,"ownership.json"),JsonConvert.SerializeObject(new {owner="UIToolkitRegression",createdUtc=DateTime.UtcNow,root=FixtureRoot,policy="New unique fake projects only; preserved for inspection."},Formatting.Indented));
            ValidationCases();WriterCases();RouteCases();
            var failures=Cases.OfType<JObject>().Count(c=>!c.Value<bool>("passed"));
            File.WriteAllText(report,JsonConvert.SerializeObject(new {completedUtc=DateTime.UtcNow,passed=Cases.Count-failures,failed=failures,total=Cases.Count,fixtureRoot=FixtureRoot,provenance=JObject.Parse(File.ReadAllText(args[1])),cases=Cases},Formatting.Indented));
            Console.WriteLine($"UIToolkit regression: {Cases.Count-failures}/{Cases.Count} passed. Fixtures: {FixtureRoot}");
            return failures==0?0:1;
        }
        static void Case(string name,Action test)
        {
            if(Filter.Length>0&&!name.Contains(Filter,StringComparison.OrdinalIgnoreCase))return;
            try { Reset();test();Cases.Add(JObject.FromObject(new{name,passed=true}));Console.WriteLine("PASS "+name); }
            catch(Exception e) { Cases.Add(JObject.FromObject(new{name,passed=false,detail=e.ToString()}));Console.WriteLine("FAIL "+name+": "+e.Message); }
        }
        static void Assert(bool value,string detail) {if(!value)throw new InvalidOperationException(detail);}
        static void Reset()
        {
            AssetDatabase.Reset();VersionControlUtility.PrepareCount=0;VersionControlUtility.Blocked=false;
            VersionControlUtility.OnPrepare=null;
            EditorApplication.isCompiling=EditorApplication.isUpdating=EditorApplication.isPlayingOrWillChangePlaymode=false;
            Debug.Errors.Clear();Selection.activeGameObject=null;
            WorkSession.OnBeginWrite=null;
            VisualTreeAsset.InstantiationCount=DataBinding.ConstructorCount=0;
        }
        static string NewProject()
        {
            var project=Path.Combine(FixtureRoot,(++Sequence).ToString("D3"));Directory.CreateDirectory(Path.Combine(project,"Assets"));Application.dataPath=Path.Combine(project,"Assets");return project;
        }
        static string Hash(byte[] value)=>WorkSession.ComputeWriteSha256(value);
        static byte[] Bytes(string value)=>new UTF8Encoding(false).GetBytes(value);
        static void Same(string path,byte[] expected)=>Assert(File.Exists(path)&&File.ReadAllBytes(path).SequenceEqual(expected),"Expected exact original bytes: "+path);
        static UIToolkitImportResult Imported()=>new(){@checked=true,assetLoaded=true,semanticValidation="passed",guid="fixture-guid"};
        static UIToolkitValidationResult Valid()=>UIToolkitValidation.ValidateUss(Uss);
        static UIToolkitAssetWriteResult Write(string path,string content,bool preview=false,Action? prepare=null,Func<UIToolkitImportResult>? import=null,bool warnings=true,UIToolkitValidationResult? validation=null)
            =>UIToolkitAssetWriter.Write("Assets/test.uss",path,Bytes(content),validation??Valid(),preview,Path.Combine(FixtureRoot,"Recovery"),prepare,import??Imported,warnings);
        static void Structural(UIToolkitValidationResult result,bool valid)
        { Assert(result.valid==valid,JsonConvert.SerializeObject(result));Assert(result.scope=="structural"&&result.semanticValidation=="not_run","Structural preflight must not claim semantic import."); }
        static void ValidationCases()
        {
            var uxmlGood=new[]{Uxml,"<UXML><VisualElement /></UXML>","<UXML xmlns=\"UnityEngine.UIElements\"><VisualElement /></UXML>","<ui:UXML xmlns:ui=\"UnityEngine.UIElements\"><ui:Template name=\"card\" src=\"card.uxml\"/><ui:Instance template=\"card\"/></ui:UXML>","<ui:UXML xmlns:ui=\"UnityEngine.UIElements\" xmlns:custom=\"App.Controls\"><custom:Widget /></ui:UXML>"};
            for(int i=0;i<uxmlGood.Length;i++){var item=uxmlGood[i];Case("uxml-valid-"+i,()=>Structural(UIToolkitValidation.ValidateUxml(item),true));}
            var uxmlBad=new[]{"","<UXML><VisualElement></UXML>","<!DOCTYPE UXML [<!ENTITY x 'expanded'>]><UXML>&x;</UXML>","<!DOCTYPE UXML SYSTEM 'file:///nonexistent-owned-fixture.dtd'><UXML />","<VisualElement />","<UXML xmlns=\"wrong.namespace\"/>","<UXML><Style/></UXML>","<UXML><Template src=\"x.uxml\"/></UXML>","<UXML><Instance/></UXML>","<UXML><VisualElement style=\"width: ;\"/></UXML>"};
            for(int i=0;i<uxmlBad.Length;i++){var item=uxmlBad[i];Case("uxml-invalid-"+i,()=>{var r=UIToolkitValidation.ValidateUxml(item);Structural(r,false);Assert(r.diagnostics.Any(d=>d.severity=="error"&&d.line>0&&d.column>0),"Positioned diagnostic required.");});}
            Case("uxml-resolved-unknown-element",()=>Structural(UIToolkitValidation.ValidateUxml("<UXML><NoSuchElement /></UXML>",(_,_)=>false),false));
            Case("uxml-duplicate-name-is-warning",()=>{var r=UIToolkitValidation.ValidateUxml("<UXML><VisualElement name=\"x\"/><Label name=\"x\"/></UXML>");Structural(r,true);Assert(r.diagnostics.Any(d=>d.code=="UXML_DUPLICATE_NAME"&&d.severity=="warning"),"Duplicate warning missing.");});
            Case("uxml-legacy-style-path-valid",()=>Structural(UIToolkitValidation.ValidateUxml("<UXML><Style path=\"UI/theme\"/></UXML>"),true));
            Case("uxml-legacy-template-path-valid",()=>Structural(UIToolkitValidation.ValidateUxml("<UXML><Template name=\"card\" path=\"UI/card\"/><Instance template=\"card\"/></UXML>"),true));
            Case("uxml-style-src-path-both-blank-invalid",()=>Structural(UIToolkitValidation.ValidateUxml("<UXML><Style src=\" \" path=\" \"/></UXML>"),false));
            Case("uxml-template-src-path-both-blank-invalid",()=>Structural(UIToolkitValidation.ValidateUxml("<UXML><Template name=\"card\" src=\" \" path=\" \"/></UXML>"),false));
            var good=new[]{Uss,"/* literal { } ; : \" */ .root { width: 12px; }",".root { --color: #efca12; color:var(--color, #ffffff); }",".root > Label, #title:hover { background-image: url(\"x;:{}/*file*/.png\"); }","@import url(\"theme.uss\"); .root{padding: 4px 8px;}",".root{ --quote: 'a\\\'b'; --path: \"x\\\\y\"; }",".root { -unity-font-style: bold; --unicode: \"Привіт\"; }","/* only a comment */",""};
            for(int i=0;i<good.Length;i++){var item=good[i];Case("uss-valid-"+i,()=>Structural(UIToolkitValidation.ValidateUss(item),true));}
            var bad=new[]{".a { width: 1px;",".a {width:1px;} }","/* unclosed", ".a { --text: \"unclosed; }", ".a { color:rgb(1,2,3; }",".a[x {width:1px;}","{width:1px;}",".a { .b {width:1px;} }","width:12px;",".a {width 12px;}",".a {width:;}",".a {width:12px height:1px;}",".a {1width:12px;}","@import url(\"x.uss\")",".a {--text: \"line\nbreak\";}"};
            for(int i=0;i<bad.Length;i++){var item=bad[i];Case("uss-invalid-"+i,()=>{var r=UIToolkitValidation.ValidateUss(item);Structural(r,false);Assert(r.diagnostics.Any(d=>d.severity=="error"&&d.line>0&&d.column>0),"Diagnostic position missing.");});}
            Case("uss-semantic-errors-remain-for-import",()=>{Structural(UIToolkitValidation.ValidateUss(".root { width: potato; unknown-property: definitelywrong; }"),true);Structural(UIToolkitValidation.ValidateUss("[name=\"x\"] {width:1px;}"),true);});
            Case("inline-parser-preserves-quoted-delimiters",()=>{var r=UIToolkitValidation.ReadInlineDeclarations("/*lead*/ --caption: \"a;b:c\"; width:var(--w,12px); background-image:url(\"x;y.png\")");Assert(r["--caption"]=="\"a;b:c\""&&r["width"]=="var(--w,12px)"&&r["background-image"]=="url(\"x;y.png\")","Quoted/function content changed.");});
            Case("inline-custom-property-case-is-preserved",()=>{var r=UIToolkitValidation.ReadInlineDeclarations("--A: 1px; --a: 2px; WIDTH: var(--A)");Assert(r["--A"]=="1px"&&r["--a"]=="2px"&&r["width"]=="var(--A)","Case-sensitive custom property identities merged.");});
            Case("uss-escaped-crlf-string-valid",()=>Structural(UIToolkitValidation.ValidateUss(".root { --caption: \"continued\\\r\nline\"; }"),true));
            Case("uss-real-source-position",()=>{var r=UIToolkitValidation.ValidateUss(".a {\n width: ;\n}");Assert(r.diagnostics.Any(d=>d.code=="USS_VALUE"&&d.line==2),"Line 2 expected.");});
        }
        static void WriterCases()
        {
            Case("import-model-explicit-unity-scope-instantiation-unrun",()=>{var r=new UIToolkitImportResult();Assert(!r.@checked&&r.semanticValidation=="not_run"&&r.semanticValidationScope=="unity_import"&&r.instantiationValidation=="not_run","Default import model implies broader validation.");});
            Case("writer-preview-has-no-side-effects",()=>{var project=NewProject();var path=Path.Combine(project,"Assets","new","test.uss");var calls=0;var r=Write(path,Uss,true,()=>calls++,()=>{calls++;return Imported();});Assert(r.succeeded&&r.status=="preview"&&!r.written&&!r.imported&&!r.mutationAttempted&&calls==0&&!Directory.Exists(Path.GetDirectoryName(path)),"Preview changed filesystem or invoked mutation/import.");});
            Case("writer-invalid-keeps-existing-source-meta",()=>{var p=Path.Combine(NewProject(),"Assets","test.uss");var before=Bytes("author baseline");var meta=Bytes("author metadata");File.WriteAllBytes(p,before);File.WriteAllBytes(p+".meta",meta);var calls=0;var r=Write(p,"invalid",false,()=>calls++,()=>{calls++;return Imported();},validation:UIToolkitValidation.ValidateUss(".a{width:;}"));Assert(!r.succeeded&&!r.written&&!r.imported&&r.status=="blocked"&&calls==0,"Invalid input mutated.");Same(p,before);Same(p+".meta",meta);});
            Case("writer-completed-exact-utf8-readback",()=>{var p=Path.Combine(NewProject(),"Assets","test.uss");var r=Write(p,Uss);Assert(r.succeeded&&r.written&&r.imported&&r.status=="completed"&&r.currentSha256==Hash(Bytes(Uss)),"Completed flags/hash incorrect.");Same(p,Bytes(Uss));});
            foreach(var mode in new[]{"errors","warnings","missing","unchecked","null","exception"})
                Case("writer-existing-failed-import-"+mode,()=>{var p=Path.Combine(NewProject(),"Assets","test.uss");var before=Bytes(".baseline{width:42px;}");var meta=Bytes("original-meta");File.WriteAllBytes(p,before);File.WriteAllBytes(p+".meta",meta);var count=0;var r=Write(p,Uss,import:()=>{count++;if(count>1)return Imported();if(mode=="exception")throw new IOException("controlled import exception");if(mode=="null")return null!;var result=Imported();if(mode=="errors")result.hasErrors=true;if(mode=="warnings")result.hasWarnings=true;if(mode=="missing")result.assetLoaded=false;if(mode=="unchecked")result.@checked=false;return result;});Assert(!r.succeeded&&r.written&&!r.imported&&r.restoredBaseline&&r.status=="restored_baseline"&&count==2&&r.restoreImport?.assetLoaded==true,"Failed import did not restore exact original/report honestly.");Same(p,before);Same(p+".meta",meta);Assert(File.Exists(Path.Combine(r.recoveryPath,"before.uss"))&&File.Exists(Path.Combine(r.recoveryPath,"candidate.uss")),"Recovery captures missing.");});
            Case("writer-warning-explicit-opt-in",()=>{var p=Path.Combine(NewProject(),"Assets","test.uss");var r=Write(p,Uss,import:()=>new(){@checked=true,assetLoaded=true,hasWarnings=true,semanticValidation="warnings"},warnings:false);Assert(r.succeeded&&r.written&&r.imported&&r.status=="completed_with_warnings"&&r.import.semanticValidation=="warnings","Warning policy not honest.");});
            Case("writer-new-import-failure-is-partial",()=>{var p=Path.Combine(NewProject(),"Assets","test.uss");var r=Write(p,Uss,import:()=>new(){@checked=true,assetLoaded=true,hasErrors=true});Assert(!r.succeeded&&r.written&&!r.imported&&!r.restoredBaseline&&r.status=="partial","New failed import must expose saved bytes/partial.");Same(p,Bytes(Uss));});
            foreach(var part in new[]{"source","meta"})Case("writer-concurrent-"+part+"-preserved",()=>{var p=Path.Combine(NewProject(),"Assets","test.uss");var before=Bytes("baseline");var author=Bytes("independent author edit");File.WriteAllBytes(p,before);File.WriteAllText(p+".meta","baseline meta");var r=Write(p,Uss,import:()=>{File.WriteAllBytes(part=="source"?p:p+".meta",author);return new(){@checked=true,assetLoaded=true,hasErrors=true};});Assert(!r.succeeded&&r.written&&!r.imported&&!r.restoredBaseline&&r.status=="partial"&&r.diagnostics.Any(d=>d.code=="BASELINE_RESTORE_REFUSED"),"Concurrent edit overwritten/hidden.");Same(part=="source"?p:p+".meta",author);Same(Path.Combine(r.recoveryPath,"before.uss"),before);});
            foreach(var part in new[]{"source","meta"})Case("writer-prepare-race-"+part+"-blocked",()=>{var p=Path.Combine(NewProject(),"Assets","test.uss");var before=Bytes("baseline");var author=Bytes("independent preparation edit");File.WriteAllBytes(p,before);File.WriteAllText(p+".meta","meta");var imports=0;var r=Write(p,Uss,prepare:()=>File.WriteAllBytes(part=="source"?p:p+".meta",author),import:()=>{imports++;return Imported();});Assert(!r.succeeded&&!r.written&&!r.imported&&imports==0,"Preparation race wrote/imported payload.");Same(part=="source"?p:p+".meta",author);if(part=="meta")Same(p,before);});
            Case("writer-new-late-meta-refuses-without-empty-source",()=>{var p=Path.Combine(NewProject(),"Assets","test.uss");var author=Bytes("new independent meta");var r=Write(p,Uss,prepare:()=>File.WriteAllBytes(p+".meta",author));Assert(!r.succeeded&&!r.written&&!r.imported&&r.status=="blocked"&&!File.Exists(p),"Late .meta must not leave empty source while claiming blocked/noWrite.");Same(p+".meta",author);});
            Case("writer-locked-existing-is-not-absence",()=>{var p=Path.Combine(NewProject(),"Assets","test.uss");var before=Bytes("locked baseline");File.WriteAllBytes(p,before);using(var locked=new FileStream(p,FileMode.Open,FileAccess.ReadWrite,FileShare.None)){var r=Write(p,Uss);Assert(!r.succeeded&&!r.written&&!r.imported&&r.status=="blocked", "Locked file treated as missing.");}Same(p,before);});
            Case("writer-checkout-denied-keeps-baseline",()=>{var p=Path.Combine(NewProject(),"Assets","test.uss");var before=Bytes("baseline");File.WriteAllBytes(p,before);var r=Write(p,Uss,prepare:()=>throw new IOException("denied"));Assert(!r.succeeded&&!r.written&&r.status=="blocked", "Checkout failure wrote.");Same(p,before);});
            Case("writer-reimport-author-change-not-restored",()=>{var p=Path.Combine(NewProject(),"Assets","test.uss");File.WriteAllText(p,"baseline");var author=Bytes("author change after recovery");var calls=0;var r=Write(p,Uss,import:()=>{if(++calls==1)return new(){@checked=true,assetLoaded=true,hasErrors=true};File.WriteAllBytes(p,author);return Imported();});Assert(!r.succeeded&&!r.restoredBaseline&&r.status=="partial"&&r.diagnostics.Any(d=>d.code=="BASELINE_CHANGED_AFTER_REIMPORT"),"Reimport changed bytes misreported restored.");Same(p,author);});
            Case("writer-stale-preimage-blocks-before-preparation",()=>{var p=Path.Combine(NewProject(),"Assets","test.uss");var author=Bytes("independently edited source B");File.WriteAllBytes(p,author);var callbacks=0;var r=UIToolkitAssetWriter.Write("Assets/test.uss",p,Bytes(Uss),Valid(),false,Path.Combine(FixtureRoot,"Recovery"),()=>callbacks++,()=>{callbacks++;return Imported();},true,Hash(Bytes("stale original A")));Assert(!r.succeeded&&!r.written&&!r.imported&&!r.mutationAttempted&&r.status=="blocked"&&callbacks==0,"Preimage mismatch prepared or wrote.");Same(p,author);});
        }
        static JObject Command(string action,string path,object? extra=null)
        {
            var args=extra==null?new JObject():JObject.FromObject(extra);args["Action"]=action;args["Path"]=path;
            var response=JObject.FromObject(ManageUIToolkit.HandleCommand(args));
            Assert(AssetDatabase.DisallowCount==AssetDatabase.AllowCount,"Auto-refresh suppression unbalanced.");return response;
        }
        static void NoMutation(JObject r,string path,bool successful=false)
        {Assert(r.Value<bool>("success")==successful&&r["data"]?.Value<bool>("written")==false&&r["data"]?.Value<bool>("imported")==false&&!File.Exists(AssetDatabase.Absolute(path))&&AssetDatabase.ImportCount==0&&AssetDatabase.FolderCount==0&&VersionControlUtility.PrepareCount==0,"NoWrite response/side effects incorrect: "+r);}
        static void RouteCases()
        {
            foreach(var action in new[]{"CreateDocument","CreateStyleSheet"})foreach(var key in new[]{"DryRun","Preview"})Case("route-preview-"+action+"-"+key,()=>{NewProject();var path="Assets/new/deeper/"+(action=="CreateDocument"?"test.uxml":"test.uss");var args=new JObject{[key]=true,["Content"]=action=="CreateDocument"?Uxml:Uss};var r=Command(action,path,args);NoMutation(r,path,true);Assert(r["data"]?.Value<string>("status")=="preview"&&r["data"]?["validation"]?.Value<string>("semanticValidation")=="not_run","Preview semantic/status dishonest.");});
            foreach(var preview in new[]{false,true})foreach(var extension in new[]{"styles.txt","styles.uxml"})Case("route-stylesheet-wrong-extension-"+extension+"-"+preview,()=>{NewProject();var path="Assets/new/"+extension;NoMutation(Command("CreateStyleSheet",path,new{Content=Uss,Preview=preview}),path);});
            var invalidInputs=new[]{"<UXML><VisualElement></UXML>","<!DOCTYPE UXML [<!ENTITY x 'x'>]><UXML>&x;</UXML>","<UXML xmlns=\"wrong\" />"};
            for(int i=0;i<invalidInputs.Length;i++){var input=invalidInputs[i];Case("route-create-invalid-"+i,()=>{NewProject();var path="Assets/new/test.uxml";NoMutation(Command("CreateDocument",path,new{Content=input}),path);});}
            foreach(var action in new[]{"ValidateUxml","ValidateUss"})Case("route-validation-content-readonly-"+action,()=>{NewProject();var r=Command(action,"",new{Content=action=="ValidateUxml"?Uxml:Uss});Assert(r.Value<bool>("success")&&r["data"]?.Value<string>("status")=="validated_structure"&&r["data"]?.Value<bool>("written")==false&&AssetDatabase.ImportCount==0&&VersionControlUtility.PrepareCount==0,"Validation mutated/imported.");});
            foreach(var mode in new[]{"null","wrongType","importedErrors","importedWarnings","logError","exception"})Case("route-import-truthful-"+mode,()=>{NewProject();var path="Assets/test.uss";AssetDatabase.OnImport=p=>{if(mode=="exception")throw new IOException("controlled importer failure");AssetDatabase.Assets[p]=mode=="null"?null:mode=="wrongType"?new VisualTreeAsset():new StyleSheet{importedWithErrors=mode=="importedErrors",importedWithWarnings=mode=="importedWarnings"};if(mode=="logError")AssetDatabase.ImportLogs[p]=new ImportLog{logEntries=new[]{new ImportLog.ImportLogEntry{flags=ImportLogFlags.Error,message="controlled importer error",file=p,line=2}}};};var r=Command("CreateStyleSheet",path,new{Content=Uss});Assert(!r.Value<bool>("success")&&r["data"]?.Value<bool>("written")==true&&r["data"]?.Value<bool>("imported")==false&&r["data"]?.Value<string>("status")=="partial","False success after Unity import failure: "+r);Same(AssetDatabase.Absolute(path),Bytes(Uss));});
            Case("route-warnings-explicit-permission",()=>{NewProject();AssetDatabase.OnImport=p=>AssetDatabase.Assets[p]=new StyleSheet{importedWithWarnings=true};var r=Command("CreateStyleSheet","Assets/test.uss",new{Content=Uss,FailOnImportWarnings=false});Assert(r.Value<bool>("success")&&r["data"]?.Value<string>("status")=="completed_with_warnings"&&r["data"]?["import"]?.Value<string>("semanticValidation")=="warnings","Warnings accepted without truthful label.");});
            foreach(var warning in new[]{false,true})Case("route-uxml-import-flag-"+(warning?"warnings":"errors"),()=>{NewProject();var path="Assets/test.uxml";AssetDatabase.OnImport=p=>AssetDatabase.Assets[p]=new VisualTreeAsset{importedWithErrors=!warning,importedWithWarnings=warning};var r=Command("CreateDocument",path,new{Content=Uxml});Assert(!r.Value<bool>("success")&&r["data"]!.Value<bool>("written")&&!r["data"]!.Value<bool>("imported")&&r["data"]!.Value<string>("status")=="partial"&&r["data"]!["import"]!.Value<bool>(warning?"hasWarnings":"hasErrors"),"VisualTreeAsset flags falsely accepted: "+r);});
            Case("route-completed-byte-count-unicode",()=>{NewProject();var r=Command("CreateDocument","Assets/test.uxml",new{Content=Uxml});Assert(r.Value<bool>("success")&&r["data"]?.Value<bool>("imported")==true&&r["data"]?.Value<int>("bytes")==Bytes(Uxml).Length&&r["data"]?.Value<string>("currentSha256")==Hash(Bytes(Uxml)),"Byte count/readback/load result wrong.");});
            foreach(var kind in new[]{"Style","Template"})Case("route-legacy-path-preview-valid-"+kind,()=>{NewProject();var content=kind=="Style"?"<UXML><Style path=\"UI/theme\"/></UXML>":"<UXML><Template name=\"card\" path=\"UI/card\"/></UXML>";var path="Assets/new/test.uxml";NoMutation(Command("CreateDocument",path,new{Content=content,Preview=true}),path,true);});
            Case("route-import-scope-does-not-claim-instantiation",()=>{foreach(var action in new[]{"CreateDocument","CreateStyleSheet"}){Reset();NewProject();var r=Command(action,action=="CreateDocument"?"Assets/test.uxml":"Assets/test.uss",new{Content=action=="CreateDocument"?Uxml:Uss});Assert(r.Value<bool>("success")&&r["data"]!["import"]!.Value<string>("semanticValidationScope")=="unity_import"&&r["data"]!["import"]!.Value<string>("instantiationValidation")=="not_run","Successful import claimed visual-tree instantiation: "+r);}});
            Case("route-runtime-binding-validate-preview-import",()=>{NewProject();var path="Assets/new/binding.uxml";var valid=Command("ValidateUxml",path,new{Content=BindingUxml});Assert(valid.Value<bool>("success")&&valid["data"]!["validation"]!.Value<bool>("valid"),"Documented Bindings/UxmlObject structural input rejected: "+valid);NoMutation(Command("CreateDocument",path,new{Content=BindingUxml,Preview=true}),path,true);var imported=Command("CreateDocument",path,new{Content=BindingUxml});Assert(imported.Value<bool>("success")&&imported["data"]!.Value<bool>("written")&&imported["data"]!.Value<bool>("imported")&&imported["data"]!["import"]!.Value<string>("instantiationValidation")=="not_run","Binding asset import incorrectly rejected or overstated: "+imported);Assert(VisualTreeAsset.InstantiationCount==0&&DataBinding.ConstructorCount==0,"Import validation ran object constructors/Instantiate.");Same(AssetDatabase.Absolute(path),Bytes(BindingUxml));});
            Case("route-custom-wrapper-and-factory-defer-to-unity",()=>{NewProject();var path="Assets/new/custom.uxml";var content="<ui:UXML xmlns:ui=\"UnityEngine.UIElements\" xmlns:custom=\"My.Controls\"><custom:Control><custom-data><custom:Model/><ui:FutureFactoryElement/></custom-data></custom:Control></ui:UXML>";var r=Command("CreateDocument",path,new{Content=content,Preview=true});NoMutation(r,path,true);Assert(r["data"]!["validation"]!.Value<string>("semanticValidation")=="not_run"&&VisualTreeAsset.InstantiationCount==0,"Custom wrapper preview was rejected or falsely constructed.");});
            foreach(var action in new[]{"AddElement","SetClasses","SetInlineStyle"})Case("route-existing-preview-preserves-"+action,()=>{NewProject();var path="Assets/test.uxml";var absolute=AssetDatabase.Absolute(path);File.WriteAllText(absolute,Uxml,new UTF8Encoding(false));File.WriteAllText(absolute+".meta","authored meta");var before=File.ReadAllBytes(absolute);var meta=File.ReadAllBytes(absolute+".meta");var r=Command(action,path,new{Preview=true,ElementName="title",ParentName="root",ElementType="Label",Text="preview",Classes=new[]{"title"},Style="width:12px"});Assert(r.Value<bool>("success")&&!r["data"]!.Value<bool>("written")&&!r["data"]!.Value<bool>("imported")&&AssetDatabase.ImportCount==0&&VersionControlUtility.PrepareCount==0,"Existing preview mutated.");Same(absolute,before);Same(absolute+".meta",meta);});
            Case("route-inline-style-preserves-quoted-values",()=>{NewProject();var path="Assets/test.uxml";File.WriteAllText(AssetDatabase.Absolute(path),Uxml);var r=Command("SetInlineStyle",path,new{ElementName="title",Style="--caption: \"a;b:c\"; width:var(--w,12px)"});Assert(r.Value<bool>("success"),"Inline edit failed: "+r);var doc=XDocument.Load(AssetDatabase.Absolute(path));var style=doc.Descendants().First(e=>e.Attribute("name")?.Value=="title").Attribute("style")!.Value;var values=UIToolkitValidation.ReadInlineDeclarations(style);Assert(values["--caption"]=="\"a;b:c\""&&values["width"]=="var(--w,12px)","Quoted literal corrupted.");});
            Case("route-existing-invalid-edit-preserves-author",()=>{NewProject();var path="Assets/test.uxml";var absolute=AssetDatabase.Absolute(path);File.WriteAllText(absolute,Uxml);var before=File.ReadAllBytes(absolute);var r=Command("SetInlineStyle",path,new{ElementName="title",Style="width:;"});Assert(!r.Value<bool>("success")&&AssetDatabase.ImportCount==0&&VersionControlUtility.PrepareCount==0,"Invalid edit mutated/imported.");Same(absolute,before);});
            Case("route-busy-editor-no-write",()=>{NewProject();EditorApplication.isCompiling=true;var path="Assets/new/test.uss";NoMutation(Command("CreateStyleSheet",path,new{Content=Uss}),path);});
            Case("route-traversal-no-write",()=>{NewProject();NoMutation(Command("CreateStyleSheet","Assets/new/../test.uss",new{Content=Uss}),"Assets/test.uss");});
            Case("route-checkout-denied-balanced-refresh",()=>{NewProject();VersionControlUtility.Blocked=true;var path="Assets/test.uss";var r=Command("CreateStyleSheet",path,new{Content=Uss});Assert(!r.Value<bool>("success")&&!r["data"]!.Value<bool>("written")&&!File.Exists(AssetDatabase.Absolute(path))&&AssetDatabase.ImportCount==0&&AssetDatabase.DisallowCount==1&&AssetDatabase.AllowCount==1,"Checkout refusal changed state or refresh suppression leaked.");});
            Case("route-refresh-release-exception-is-partial",()=>{NewProject();AssetDatabase.OnAllowAutoRefresh=()=>throw new IOException("controlled release failure");var r=Command("CreateStyleSheet","Assets/test.uss",new{Content=Uss});Assert(!r.Value<bool>("success")&&r["data"]!.Value<bool>("written")&&r["data"]!.Value<string>("status")=="partial"&&r["data"]!["diagnostics"]!.Any(d=>d.Value<string>("code")=="AUTO_REFRESH_RELEASE_FAILED"),"Scope release exception hid already written bytes: "+r);Same(AssetDatabase.Absolute("Assets/test.uss"),Bytes(Uss));});
            Case("route-postimport-source-change-is-preserved",()=>{NewProject();var path="Assets/test.uss";var author=Bytes("independent post-import source");AssetDatabase.OnAllowAutoRefresh=()=>File.WriteAllBytes(AssetDatabase.Absolute(path),author);var r=Command("CreateStyleSheet",path,new{Content=Uss});Assert(!r.Value<bool>("success")&&r["data"]!.Value<bool>("written")&&!r["data"]!.Value<bool>("imported")&&r["data"]!.Value<string>("status")=="partial"&&r["data"]!["diagnostics"]!.Any(d=>d.Value<string>("code")=="FINAL_SOURCE_CHANGED"),"Postscope edit falsely reported successful import: "+r);Same(AssetDatabase.Absolute(path),author);});
            foreach(var action in new[]{"AddElement","SetClasses","SetInlineStyle"})Case("route-stale-source-preimage-refused-"+action,()=>{NewProject();var path="Assets/test.uxml";var absolute=AssetDatabase.Absolute(path);File.WriteAllText(absolute,Uxml);var independent=Bytes(Uxml.Replace("Привіт","Автор").Replace("Вітаю","Автор"));File.WriteAllText(absolute+".meta","authored metadata");var meta=File.ReadAllBytes(absolute+".meta");WorkSession.OnBeginWrite=()=>File.WriteAllBytes(absolute,independent);var r=Command(action,path,new{ParentName="root",ElementName="title",ElementType="Label",Classes=new[]{"new-class"},Style="width:12px"});Assert(!r.Value<bool>("success")&&!r["data"]!.Value<bool>("written")&&!r["data"]!.Value<bool>("imported")&&AssetDatabase.ImportCount==0&&VersionControlUtility.PrepareCount==0,"Stale source edit overwrote independent source: "+r);Same(absolute,independent);Same(absolute+".meta",meta);});
            foreach(var action in new[]{"AddElement","SetClasses","SetInlineStyle"})Case("route-checkout-source-race-refused-"+action,()=>{NewProject();var path="Assets/test.uxml";var absolute=AssetDatabase.Absolute(path);File.WriteAllText(absolute,Uxml);var independent=Bytes(Uxml.Replace("Вітаю","Автор"));var callback=false;VersionControlUtility.OnPrepare=()=>{callback=true;File.WriteAllBytes(absolute,independent);};var r=Command(action,path,new{ParentName="root",ElementName="title",ElementType="Label",Classes=new[]{"new-class"},Style="width:12px"});Assert(callback,"Source-race boundary callback did not execute.");Assert(File.ReadAllBytes(absolute).SequenceEqual(independent),"Checkout boundary author bytes were overwritten. currentSha256="+Hash(File.ReadAllBytes(absolute))+" authorSha256="+Hash(independent)+" response="+r);Assert(!r.Value<bool>("success")&&!r["data"]!.Value<bool>("written")&&!r["data"]!.Value<bool>("imported")&&AssetDatabase.ImportCount==0,"Checkout race was falsely successful: "+r);});
        }
    }
}
