#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;

namespace Cidonix.UniBridge.MCP.Editor.Tools
{
    /// <summary>
    /// Curated tool allow-list and aliases shared by batch execution and agent-facing guides.
    /// </summary>
    internal static class BatchActionToolCatalog
    {
        static readonly HashSet<string> s_AllowedTools = new(StringComparer.Ordinal)
        {
            "UniBridge_ManageGameObject",
            "UniBridge_ManageAsset",
            "UniBridge_ManageAssetImporter",
            "UniBridge_ManageMaterial",
            "UniBridge_ManageScriptableObject",
            "UniBridge_ManageScene",
            "UniBridge_ManagePrefab",
            "UniBridge_ManageAnimatorController",
            "UniBridge_ManageAnimationClip",
            "UniBridge_ManageUI",
            "UniBridge_ManageUnityEvent",
            "UniBridge_ManageEditor",
            "UniBridge_ManageShader",
            "UniBridge_ScopedEdit",
            "UniBridge_BehaviourContext",
            "UniBridge_ManageTilemap2D",
            "UniBridge_ManageInputActions",
            "UniBridge_ManageTimeline",
            "UniBridge_ManageConstraints",
            "UniBridge_ManagePhysics2D",
            "UniBridge_DomainCatalog",
            "UniBridge_ManagePhysics3D",
            "UniBridge_ManageNavigation",
            "UniBridge_ManageRendering",
            "UniBridge_ManageAudio",
            "UniBridge_ManageVFX",
            "UniBridge_ManageUIToolkit",
            "UniBridge_AssetIntelligence",
            "UniBridge_ScriptIntelligence",
            "UniBridge_Discover",
            "UniBridge_ValidateAdditiveSceneRegistration",
            "UniBridge_ValidateScript",
            "UniBridge_CaptureView",
            "UniBridge_CaptureAsset",
            "UniBridge_CaptureUIToolkit",
            "UniBridge_VisualSceneAudit",
            "UniBridge_SceneObjectView",
            "UniBridge_SceneHierarchyExport",
            "UniBridge_ManageSceneHierarchy",
            "UniBridge_TypeSchema",
            "UniBridge_UnitySearch",
            "UniBridge_ContextSnapshot",
            "UniBridge_EditorEvents",
            "UniBridge_EditorSnapshot",
            "UniBridge_RuntimeProfiler",
            "UniBridge_RuntimeStateProbe",
            "UniBridge_ToolGuide",
            "UniBridge_ReadConsole"
        };

        static readonly Dictionary<string, string> s_ToolAliases = new(StringComparer.OrdinalIgnoreCase)
        {
            ["game_object"] = "UniBridge_ManageGameObject",
            ["gameobject"] = "UniBridge_ManageGameObject",
            ["go"] = "UniBridge_ManageGameObject",
            ["objects"] = "UniBridge_ManageGameObject",
            ["asset"] = "UniBridge_ManageAsset",
            ["assets"] = "UniBridge_ManageAsset",
            ["asset_importer"] = "UniBridge_ManageAssetImporter",
            ["assetimporter"] = "UniBridge_ManageAssetImporter",
            ["importer"] = "UniBridge_ManageAssetImporter",
            ["import_settings"] = "UniBridge_ManageAssetImporter",
            ["importsettings"] = "UniBridge_ManageAssetImporter",
            ["importer_settings"] = "UniBridge_ManageAssetImporter",
            ["material"] = "UniBridge_ManageMaterial",
            ["materials"] = "UniBridge_ManageMaterial",
            ["mat"] = "UniBridge_ManageMaterial",
            ["mats"] = "UniBridge_ManageMaterial",
            ["material_settings"] = "UniBridge_ManageMaterial",
            ["materialsettings"] = "UniBridge_ManageMaterial",
            ["scriptable_object"] = "UniBridge_ManageScriptableObject",
            ["scriptableobject"] = "UniBridge_ManageScriptableObject",
            ["scriptable"] = "UniBridge_ManageScriptableObject",
            ["so"] = "UniBridge_ManageScriptableObject",
            ["data_asset"] = "UniBridge_ManageScriptableObject",
            ["config_asset"] = "UniBridge_ManageScriptableObject",
            ["scene"] = "UniBridge_ManageScene",
            ["prefab"] = "UniBridge_ManagePrefab",
            ["animator"] = "UniBridge_ManageAnimatorController",
            ["animator_controller"] = "UniBridge_ManageAnimatorController",
            ["controller"] = "UniBridge_ManageAnimatorController",
            ["animation_clip"] = "UniBridge_ManageAnimationClip",
            ["animationclip"] = "UniBridge_ManageAnimationClip",
            ["anim_clip"] = "UniBridge_ManageAnimationClip",
            ["clip"] = "UniBridge_ManageAnimationClip",
            ["scoped_edit"] = "UniBridge_ScopedEdit",
            ["scopededit"] = "UniBridge_ScopedEdit",
            ["scope"] = "UniBridge_ScopedEdit",
            ["scope_edit"] = "UniBridge_ScopedEdit",
            ["behaviour_context"] = "UniBridge_BehaviourContext",
            ["behavior_context"] = "UniBridge_BehaviourContext",
            ["monobehaviour_context"] = "UniBridge_BehaviourContext",
            ["script_context"] = "UniBridge_BehaviourContext",
            ["attached_scripts"] = "UniBridge_BehaviourContext",
            ["tilemap"] = "UniBridge_ManageTilemap2D",
            ["tilemap2d"] = "UniBridge_ManageTilemap2D",
            ["tiles"] = "UniBridge_ManageTilemap2D",
            ["tile"] = "UniBridge_ManageTilemap2D",
            ["grid2d"] = "UniBridge_ManageTilemap2D",
            ["input_actions"] = "UniBridge_ManageInputActions",
            ["inputactions"] = "UniBridge_ManageInputActions",
            ["input"] = "UniBridge_ManageInputActions",
            ["player_input"] = "UniBridge_ManageInputActions",
            ["playerinput"] = "UniBridge_ManageInputActions",
            ["timeline"] = "UniBridge_ManageTimeline",
            ["playable"] = "UniBridge_ManageTimeline",
            ["playable_director"] = "UniBridge_ManageTimeline",
            ["playabledirector"] = "UniBridge_ManageTimeline",
            ["cinematic"] = "UniBridge_ManageTimeline",
            ["constraints"] = "UniBridge_ManageConstraints",
            ["constraint"] = "UniBridge_ManageConstraints",
            ["animation_constraints"] = "UniBridge_ManageConstraints",
            ["parent_constraint"] = "UniBridge_ManageConstraints",
            ["position_constraint"] = "UniBridge_ManageConstraints",
            ["rotation_constraint"] = "UniBridge_ManageConstraints",
            ["lookat_constraint"] = "UniBridge_ManageConstraints",
            ["physics2d"] = "UniBridge_ManagePhysics2D",
            ["2d_physics"] = "UniBridge_ManagePhysics2D",
            ["collider2d"] = "UniBridge_ManagePhysics2D",
            ["rigidbody2d"] = "UniBridge_ManagePhysics2D",
            ["joint2d"] = "UniBridge_ManagePhysics2D",
            ["effector2d"] = "UniBridge_ManagePhysics2D",
            ["domain_catalog"] = "UniBridge_DomainCatalog",
            ["domaincatalog"] = "UniBridge_DomainCatalog",
            ["domains"] = "UniBridge_DomainCatalog",
            ["domain"] = "UniBridge_DomainCatalog",
            ["tool_domains"] = "UniBridge_DomainCatalog",
            ["physics3d"] = "UniBridge_ManagePhysics3D",
            ["3d_physics"] = "UniBridge_ManagePhysics3D",
            ["collider3d"] = "UniBridge_ManagePhysics3D",
            ["rigidbody3d"] = "UniBridge_ManagePhysics3D",
            ["joint3d"] = "UniBridge_ManagePhysics3D",
            ["physic_material"] = "UniBridge_ManagePhysics3D",
            ["navigation"] = "UniBridge_ManageNavigation",
            ["nav"] = "UniBridge_ManageNavigation",
            ["navmesh"] = "UniBridge_ManageNavigation",
            ["navmesh_agent"] = "UniBridge_ManageNavigation",
            ["navmeshagent"] = "UniBridge_ManageNavigation",
            ["navmesh_surface"] = "UniBridge_ManageNavigation",
            ["navmeshsurface"] = "UniBridge_ManageNavigation",
            ["rendering"] = "UniBridge_ManageRendering",
            ["render"] = "UniBridge_ManageRendering",
            ["camera"] = "UniBridge_ManageRendering",
            ["lighting"] = "UniBridge_ManageRendering",
            ["lights"] = "UniBridge_ManageRendering",
            ["volume"] = "UniBridge_ManageRendering",
            ["render_settings"] = "UniBridge_ManageRendering",
            ["rendersettings"] = "UniBridge_ManageRendering",
            ["pixel_perfect"] = "UniBridge_ManageRendering",
            ["pixelperfect"] = "UniBridge_ManageRendering",
            ["light2d"] = "UniBridge_ManageRendering",
            ["shadowcaster2d"] = "UniBridge_ManageRendering",
            ["2d_rendering"] = "UniBridge_ManageRendering",
            ["audio"] = "UniBridge_ManageAudio",
            ["scene_audio"] = "UniBridge_ManageAudio",
            ["audio_source"] = "UniBridge_ManageAudio",
            ["audiosource"] = "UniBridge_ManageAudio",
            ["audio_listener"] = "UniBridge_ManageAudio",
            ["audiolistener"] = "UniBridge_ManageAudio",
            ["audio_filter"] = "UniBridge_ManageAudio",
            ["vfx"] = "UniBridge_ManageVFX",
            ["visual_effect"] = "UniBridge_ManageVFX",
            ["visualeffect"] = "UniBridge_ManageVFX",
            ["particle_system"] = "UniBridge_ManageVFX",
            ["particlesystem"] = "UniBridge_ManageVFX",
            ["particles"] = "UniBridge_ManageVFX",
            ["trail_renderer"] = "UniBridge_ManageVFX",
            ["trailrenderer"] = "UniBridge_ManageVFX",
            ["line_renderer"] = "UniBridge_ManageVFX",
            ["linerenderer"] = "UniBridge_ManageVFX",
            ["video_player"] = "UniBridge_ManageVFX",
            ["videoplayer"] = "UniBridge_ManageVFX",
            ["uitoolkit"] = "UniBridge_ManageUIToolkit",
            ["ui_toolkit"] = "UniBridge_ManageUIToolkit",
            ["uxml_authoring"] = "UniBridge_ManageUIToolkit",
            ["uss"] = "UniBridge_ManageUIToolkit",
            ["uidocument"] = "UniBridge_ManageUIToolkit",
            ["ui"] = "UniBridge_ManageUI",
            ["rect_transform"] = "UniBridge_ManageUI",
            ["recttransform"] = "UniBridge_ManageUI",
            ["canvas"] = "UniBridge_ManageUI",
            ["layout"] = "UniBridge_ManageUI",
            ["unity_event"] = "UniBridge_ManageUnityEvent",
            ["unityevent"] = "UniBridge_ManageUnityEvent",
            ["events"] = "UniBridge_ManageUnityEvent",
            ["event"] = "UniBridge_ManageUnityEvent",
            ["persistent_event"] = "UniBridge_ManageUnityEvent",
            ["persistent_call"] = "UniBridge_ManageUnityEvent",
            ["editor"] = "UniBridge_ManageEditor",
            ["manage_editor"] = "UniBridge_ManageEditor",
            ["project_operations"] = "UniBridge_ManageEditor",
            ["lifecycle"] = "UniBridge_ManageEditor",
            ["selection"] = "UniBridge_ManageEditor",
            ["select"] = "UniBridge_ManageEditor",
            ["ready"] = "UniBridge_ManageEditor",
            ["wait_ready"] = "UniBridge_ManageEditor",
            ["wait_idle"] = "UniBridge_ManageEditor",
            ["save_all"] = "UniBridge_ManageEditor",
            ["save_assets"] = "UniBridge_ManageEditor",
            ["compile"] = "UniBridge_ManageEditor",
            ["exit_play_mode"] = "UniBridge_ManageEditor",
            ["shader"] = "UniBridge_ManageShader",
            ["asset_intelligence"] = "UniBridge_AssetIntelligence",
            ["assetintel"] = "UniBridge_AssetIntelligence",
            ["asset_search"] = "UniBridge_AssetIntelligence",
            ["asset_ref_search"] = "UniBridge_AssetIntelligence",
            ["asset_reference_search"] = "UniBridge_AssetIntelligence",
            ["asset_usages"] = "UniBridge_AssetIntelligence",
            ["reference_graph"] = "UniBridge_AssetIntelligence",
            ["reference_locations"] = "UniBridge_AssetIntelligence",
            ["asset_structure"] = "UniBridge_AssetIntelligence",
            ["prefab_structure"] = "UniBridge_AssetIntelligence",
            ["scene_asset_structure"] = "UniBridge_AssetIntelligence",
            ["structure_search"] = "UniBridge_AssetIntelligence",
            ["serialized_asset_search"] = "UniBridge_AssetIntelligence",
            ["read_yaml"] = "UniBridge_AssetIntelligence",
            ["script_intelligence"] = "UniBridge_ScriptIntelligence",
            ["scriptintel"] = "UniBridge_ScriptIntelligence",
            ["script_search"] = "UniBridge_ScriptIntelligence",
            ["script_usages"] = "UniBridge_ScriptIntelligence",
            ["code_usages"] = "UniBridge_ScriptIntelligence",
            ["unity_code_usages"] = "UniBridge_ScriptIntelligence",
            ["discover"] = "UniBridge_Discover",
            ["ping"] = "UniBridge_Discover",
            ["unibridge"] = "UniBridge_Discover",
            ["mcp_ping"] = "UniBridge_Discover",
            ["tool_discovery"] = "UniBridge_Discover",
            ["validate_additive_scene"] = "UniBridge_ValidateAdditiveSceneRegistration",
            ["validate_additive_scene_registration"] = "UniBridge_ValidateAdditiveSceneRegistration",
            ["additive_scene_validation"] = "UniBridge_ValidateAdditiveSceneRegistration",
            ["additive_scene_registration"] = "UniBridge_ValidateAdditiveSceneRegistration",
            ["scene_registration"] = "UniBridge_ValidateAdditiveSceneRegistration",
            ["scene_metadata_validation"] = "UniBridge_ValidateAdditiveSceneRegistration",
            ["validate_script"] = "UniBridge_ValidateScript",
            ["validatescript"] = "UniBridge_ValidateScript",
            ["script_validation"] = "UniBridge_ValidateScript",
            ["script_validate"] = "UniBridge_ValidateScript",
            ["validate_cs"] = "UniBridge_ValidateScript",
            ["cs_validation"] = "UniBridge_ValidateScript",
            ["capture"] = "UniBridge_CaptureView",
            ["vision"] = "UniBridge_CaptureView",
            ["visual_audit"] = "UniBridge_VisualSceneAudit",
            ["visual_scene_audit"] = "UniBridge_VisualSceneAudit",
            ["scene_audit"] = "UniBridge_VisualSceneAudit",
            ["presentation_audit"] = "UniBridge_VisualSceneAudit",
            ["self_check"] = "UniBridge_VisualSceneAudit",
            ["visual_qa"] = "UniBridge_VisualSceneAudit",
            ["asset_capture"] = "UniBridge_CaptureAsset",
            ["capture_asset"] = "UniBridge_CaptureAsset",
            ["asset_preview"] = "UniBridge_CaptureAsset",
            ["render_asset"] = "UniBridge_CaptureAsset",
            ["asset_vision"] = "UniBridge_CaptureAsset",
            ["asset_grid"] = "UniBridge_CaptureAsset",
            ["capture_grid"] = "UniBridge_CaptureAsset",
            ["asset_contact_sheet"] = "UniBridge_CaptureAsset",
            ["asset_multiview"] = "UniBridge_CaptureAsset",
            ["contact_sheet"] = "UniBridge_CaptureAsset",
            ["browse_assets"] = "UniBridge_CaptureAsset",
            ["uitoolkit_capture"] = "UniBridge_CaptureUIToolkit",
            ["capture_uitoolkit"] = "UniBridge_CaptureUIToolkit",
            ["ui_toolkit_capture"] = "UniBridge_CaptureUIToolkit",
            ["uxml_capture"] = "UniBridge_CaptureUIToolkit",
            ["capture_uxml"] = "UniBridge_CaptureUIToolkit",
            ["uxml"] = "UniBridge_CaptureUIToolkit",
            ["scene_view"] = "UniBridge_SceneObjectView",
            ["scene_object_view"] = "UniBridge_SceneObjectView",
            ["object_view"] = "UniBridge_SceneObjectView",
            ["view_object"] = "UniBridge_SceneObjectView",
            ["view_objects"] = "UniBridge_SceneObjectView",
            ["view_gameobjects"] = "UniBridge_SceneObjectView",
            ["hierarchy_view"] = "UniBridge_SceneObjectView",
            ["scene_hierarchy_export"] = "UniBridge_SceneHierarchyExport",
            ["hierarchy_export"] = "UniBridge_SceneHierarchyExport",
            ["full_hierarchy"] = "UniBridge_SceneHierarchyExport",
            ["large_scene_export"] = "UniBridge_SceneHierarchyExport",
            ["scene_diff"] = "UniBridge_SceneHierarchyExport",
            ["hierarchy_diff"] = "UniBridge_SceneHierarchyExport",
            ["scene_hierarchy"] = "UniBridge_ManageSceneHierarchy",
            ["manage_scene_hierarchy"] = "UniBridge_ManageSceneHierarchy",
            ["hierarchy_edit"] = "UniBridge_ManageSceneHierarchy",
            ["batch_reparent"] = "UniBridge_ManageSceneHierarchy",
            ["reparent_batch"] = "UniBridge_ManageSceneHierarchy",
            ["organize_scene"] = "UniBridge_ManageSceneHierarchy",
            ["scene_container"] = "UniBridge_ManageSceneHierarchy",
            ["type_schema"] = "UniBridge_TypeSchema",
            ["typeschema"] = "UniBridge_TypeSchema",
            ["component_schema"] = "UniBridge_TypeSchema",
            ["componentschema"] = "UniBridge_TypeSchema",
            ["schema"] = "UniBridge_TypeSchema",
            ["shader_schema"] = "UniBridge_TypeSchema",
            ["importer_schema"] = "UniBridge_TypeSchema",
            ["asset_schema"] = "UniBridge_TypeSchema",
            ["patch_examples"] = "UniBridge_TypeSchema",
            ["property_examples"] = "UniBridge_TypeSchema",
            ["unity_search"] = "UniBridge_UnitySearch",
            ["unified_search"] = "UniBridge_UnitySearch",
            ["find"] = "UniBridge_UnitySearch",
            ["lookup"] = "UniBridge_UnitySearch",
            ["project_search"] = "UniBridge_UnitySearch",
            ["scene_search"] = "UniBridge_UnitySearch",
            ["context"] = "UniBridge_ContextSnapshot",
            ["snapshot"] = "UniBridge_ContextSnapshot",
            ["editor_events"] = "UniBridge_EditorEvents",
            ["events"] = "UniBridge_EditorEvents",
            ["event_deltas"] = "UniBridge_EditorEvents",
            ["selection_events"] = "UniBridge_EditorEvents",
            ["asset_events"] = "UniBridge_EditorEvents",
            ["compile_events"] = "UniBridge_EditorEvents",
            ["editor_snapshot"] = "UniBridge_EditorSnapshot",
            ["editorsnapshot"] = "UniBridge_EditorSnapshot",
            ["editor_state"] = "UniBridge_EditorSnapshot",
            ["workspace_snapshot"] = "UniBridge_EditorSnapshot",
            ["runtime_profiler"] = "UniBridge_RuntimeProfiler",
            ["runtimeprofiler"] = "UniBridge_RuntimeProfiler",
            ["runtime"] = "UniBridge_RuntimeProfiler",
            ["runtime_snapshot"] = "UniBridge_RuntimeProfiler",
            ["profiler"] = "UniBridge_RuntimeProfiler",
            ["performance"] = "UniBridge_RuntimeProfiler",
            ["perf"] = "UniBridge_RuntimeProfiler",
            ["fps"] = "UniBridge_RuntimeProfiler",
            ["frame_time"] = "UniBridge_RuntimeProfiler",
            ["spikes"] = "UniBridge_RuntimeProfiler",
            ["gc_profile"] = "UniBridge_RuntimeProfiler",
            ["memory_profile"] = "UniBridge_RuntimeProfiler",
            ["playmode_profiler"] = "UniBridge_RuntimeProfiler",
            ["runtime_probe"] = "UniBridge_RuntimeStateProbe",
            ["runtimestateprobe"] = "UniBridge_RuntimeStateProbe",
            ["runtime_state"] = "UniBridge_RuntimeStateProbe",
            ["runtime_state_probe"] = "UniBridge_RuntimeStateProbe",
            ["state_probe"] = "UniBridge_RuntimeStateProbe",
            ["probe_state"] = "UniBridge_RuntimeStateProbe",
            ["watch_state"] = "UniBridge_RuntimeStateProbe",
            ["watch_variables"] = "UniBridge_RuntimeStateProbe",
            ["watch_assert"] = "UniBridge_RuntimeStateProbe",
            ["runtime_assert"] = "UniBridge_RuntimeStateProbe",
            ["state_assert"] = "UniBridge_RuntimeStateProbe",
            ["expect_state"] = "UniBridge_RuntimeStateProbe",
            ["variables"] = "UniBridge_RuntimeStateProbe",
            ["fields"] = "UniBridge_RuntimeStateProbe",
            ["component_state"] = "UniBridge_RuntimeStateProbe",
            ["monobehaviour_state"] = "UniBridge_RuntimeStateProbe",
            ["behaviour_state"] = "UniBridge_RuntimeStateProbe",
            ["runtime_fields"] = "UniBridge_RuntimeStateProbe",
            ["playmode_state_probe"] = "UniBridge_RuntimeStateProbe",
            ["guide"] = "UniBridge_ToolGuide",
            ["tool_guide"] = "UniBridge_ToolGuide",
            ["toolguide"] = "UniBridge_ToolGuide",
            ["help"] = "UniBridge_ToolGuide",
            ["workflow"] = "UniBridge_ToolGuide",
            ["console"] = "UniBridge_ReadConsole",
            ["read_console"] = "UniBridge_ReadConsole",
            ["readconsole"] = "UniBridge_ReadConsole",
            ["logs"] = "UniBridge_ReadConsole",
            ["diagnostics"] = "UniBridge_ReadConsole"
        };

        public static IReadOnlyCollection<string> AllowedTools => s_AllowedTools;

        public static IReadOnlyDictionary<string, string> ToolAliases => s_ToolAliases;

        public static bool IsAllowed(string toolName)
        {
            return !string.IsNullOrWhiteSpace(toolName) && s_AllowedTools.Contains(toolName);
        }

        public static string ResolveToolName(string rawTool)
        {
            if (string.IsNullOrWhiteSpace(rawTool))
            {
                return null;
            }

            var trimmed = rawTool.Trim();
            if (s_AllowedTools.Contains(trimmed))
            {
                return trimmed;
            }

            if (s_ToolAliases.TryGetValue(trimmed, out var alias))
            {
                return alias;
            }

            return trimmed.StartsWith("UniBridge_", StringComparison.Ordinal)
                ? trimmed
                : trimmed;
        }

        public static string[] GetAliasesForTool(string toolName)
        {
            if (string.IsNullOrWhiteSpace(toolName))
            {
                return Array.Empty<string>();
            }

            return s_ToolAliases
                .Where(pair => string.Equals(pair.Value, toolName, StringComparison.Ordinal))
                .Select(pair => pair.Key)
                .OrderBy(alias => alias, StringComparer.OrdinalIgnoreCase)
                .ToArray();
        }
    }
}
